language: crystal
script:
  - crystal tool format --check
  - crystal spec
  - crystal docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
